name: Backend Deploy to Cloud Run

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
  workflow_dispatch:

env:
  PROJECT_ID: todo-backend-488906
  REGION: asia-south1
  SERVICE: auth-service
  IMAGE: asia-south1-docker.pkg.dev/todo-backend-488906/cloudrun-repos/auth-service

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v4

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          token_format: 'access_token'
          workload_identity_provider: '${{ secrets.WIF_PROVIDER }}'
          service_account: '${{ secrets.WIF_SERVICE_ACCOUNT }}'

      - name: Docker Auth
        uses: docker/login-action@v3
        with:
          registry: asia-south1-docker.pkg.dev
          username: oauth2accesstoken
          password: '${{ steps.auth.outputs.access_token }}'

      - name: Build and Push
        run: |-
          docker build -t "${{ env.IMAGE }}:${{ github.sha }}" ./backend
          docker push "${{ env.IMAGE }}:${{ github.sha }}"

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: '${{ env.SERVICE }}'
          region: '${{ env.REGION }}'
          image: '${{ env.IMAGE }}:${{ github.sha }}'
          flags: '--allow-unauthenticated'
